### PR TITLE
2 include space info

### LINKED ISSUE #2: Owner can include name, description, price to space
As an Owner,
So I can entice potential guests to book my space,
I want to include a name, a short description, and a price per night

### PR DESCRIPTION
**Pull request by RSijelmass**
Close #2 - unit and feature tested

### CODE REVIEW

**Comment by RSijelmass** [comment]
Pulled merged branch, everything seems to work!

**Comment by kkavita92** [comment]
Plz delete nyc_output.json file

**Comment by kkavita92** [comment]
Good work TEAM

**Comment by RSijelmass** [comment]
YOUR .nyc_output has been removed. You're welcome.

**Comment by kkavita92** [comment]
You mean the one CHARLOTTE merged?

**Pull request merged**
